title: Deltarune Script Project
# email: your-email@example.com
description: >-
  A project aimed at creating a complete script of Deltarune by Toby Fox.
baseurl: "/deltascript"
url: "https://wovenstarlight.github.io"
github: "https://github.com/wovenstarlight/deltascript"

# Build settings
# plugins:
#   - jekyll-feed

# Front matter defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# Exclude from processing.
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .vscode/
  - contribute/*.md